// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6gNbTGQmfZBY_00VauyrxbunEyH7Sn6g',
    appId: '1:639845792831:web:3a04014d4d7ddf996c0c8a',
    messagingSenderId: '639845792831',
    projectId: 'loginmadeasy',
    authDomain: 'loginmadeasy.firebaseapp.com',
    storageBucket: 'loginmadeasy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXJ4tKXlSe-d6D9gG4TMAe6fZqH_eIOMA',
    appId: '1:639845792831:android:8362a56221ae93dd6c0c8a',
    messagingSenderId: '639845792831',
    projectId: 'loginmadeasy',
    storageBucket: 'loginmadeasy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGb9pamlLqrvVbf1Abqbt-bwRnM7ugAJs',
    appId: '1:639845792831:ios:2126df98722183076c0c8a',
    messagingSenderId: '639845792831',
    projectId: 'loginmadeasy',
    storageBucket: 'loginmadeasy.appspot.com',
    androidClientId: '639845792831-b4uhuol8iqotmkjkhjgfaratmof18ftb.apps.googleusercontent.com',
    iosClientId: '639845792831-odnqd2njdlg71j76itpdnn4cat7ebqs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginProjectTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGb9pamlLqrvVbf1Abqbt-bwRnM7ugAJs',
    appId: '1:639845792831:ios:1e3e27d8fb7489c86c0c8a',
    messagingSenderId: '639845792831',
    projectId: 'loginmadeasy',
    storageBucket: 'loginmadeasy.appspot.com',
    androidClientId: '639845792831-b4uhuol8iqotmkjkhjgfaratmof18ftb.apps.googleusercontent.com',
    iosClientId: '639845792831-v58u8gnmvo53t599unsrv4ue1hgto4nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginProjectTest1.RunnerTests',
  );
}
